version: 0.0
os: linux
files:
  - source: wordpress
    destination: /var/www/html/wordpress
  - source: configs/nginx/default.conf
    destination: /etc/nginx/conf.d/
  - source: configs/php/99-php-includes.ini
    destination: /etc/php.d/
  - source: configs/php/www.conf
    destination: /etc/php-fpm.d/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: deploy-scripts/file-permissions.sh
      timeout: 300
      runas: root
    - location: deploy-scripts/reload-services.sh
      timeout: 300
      runas: root
