version: 0.0
os: linux
files:
  - source: wordpress
    destination: /var/www/html/wordpress
  - source: configs/nginx/default.conf
    destination: /etc/nginx/conf.d/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/wordpress
    pattern: "*"
    owner: nobody
    group: nobody
    mode: 755
    type:
      - file
  - object: /var/www/html/wordpress
    pattern: "*"
    owner: nobody
    group: nobody
    mode: 755
    type:
      - directory
  - object: /var/www/html/wordpress/wp-content/uploads
    pattern: "*"
    owner: nginx
    group: nginx
    mode: 755
    type:
      - file
  - object: /var/www/html/wordpress/wp-content/uploads
    pattern: "*"
    owner: nginx
    group: nginx
    mode: 755
    type:
      - directory
hooks:
  AfterInstall:
    - location: deploy-scripts/reload-services.sh
      timeout: 300
      runas: root
